ALTER TABLE `item`
CHANGE COLUMN `id` `id` VARCHAR(20) NOT NULL ;

ALTER TABLE `item`
ADD COLUMN `success_url` VARCHAR(200) NULL DEFAULT NULL AFTER `view_count`,
ADD COLUMN `cancel_url` VARCHAR(200) NULL DEFAULT NULL AFTER `success_url`,
ADD COLUMN `download_file` VARCHAR(200) NULL DEFAULT NULL AFTER `cancel_url`,
ADD COLUMN `buy_now` TEXT NULL DEFAULT NULL AFTER `download_file`;

ALTER TABLE `item`
ADD COLUMN `product` TINYINT(4) NULL DEFAULT NULL AFTER `buy_now`;